thk-test2/SSD-CodeClimbers

- Testshell/Testshell.sln
- Testshell/main.cpp
- Testshell/test.cpp
TestShell의 공통 함수 및 변수 뼈대 작성
- run() 작성
- executeCommand() 뼈대 작성
- Command Class 선언
- Debug, Release 모드 구분을 통한 unit test 분기 작성
> [Feature] Add TestShell class common method and variable

- Testshell/main.cpp
- Testshell/test_shell.cpp
- TestShell의 fullread() 함수 구현
- TestShell의 fullwrite() 함수 구현
- LBA 끝까지 while문을 돌면서 read/write 수행
- Unit Test 추가
> [feature] TestShell fullread, fullwrite 구현

- Testshell/main.cpp
- Testshell/test_shell.cpp
- 리팩토링
- 불필요한 멤버 함수 제거 후 std 라이브러리 함수 사용
- 테스트 fixture 하나로 통일
> [refactoring] Remove unnecessary func and merge test fixture

- Testshell/SSD_EXE.cpp
- Testshell/SSD_EXE_test.cpp
- Testshell/Testshell.vcxproj
- Testshell/Testshell.vcxproj.filters
- Testshell/command.h
- Testshell/exit_command.cpp
- Testshell/fullread_command.cpp
- Testshell/fullwrite_command.cpp
- Testshell/help_command.cpp
- Testshell/main.cpp
- Testshell/read_command.cpp
- Testshell/ssd_interface.h
- Testshell/test_script_command.cpp
- Testshell/test_shell.cpp
- Testshell/test_shell.h
- Testshell/write_command.cpp
- 커맨드 추가 요구사항이 있을 경우를 대비
- factory 패턴 적용한 command interface 도입
- 커맨드 별 cpp 파일 분리
> [refactoring] command handler class

- SSD/file_iostream.cpp
- SSD/file_iostream.h
- SSD/ssd_driver.cpp
- SSD/ssd_driver.h
- SSD/ssd_driver_test.cpp
- SSD에 erase 추가하였습니다.
- erase command로 nand.txt가 0x00000000으로 업데이트됩니다
- erase 범위 error시 output.txt에 ERROR
> [feature] add SSD erase command

- Testshell/Testshell.vcxproj
- Testshell/file_system_interface.cpp
- Testshell/file_system_interface.h
- Testshell/logger.cpp
- Testshell/logger.h
- Testshell/logger_test.cpp
- Testshell/test_shell.cpp
- Logger 기능 추가
- Logger class 구현
- singleton design pattern 적용
- 유닛 테스트를 위한 file system class 멤버변수로 포함
- print()
- rotate() 관련
- 타임스탬프 관련
- txt -> zip 변경 함수
- unit test를 위한 logger class가 사용하는 file system interface 구현
- 파일 생성/쓰기
- 파일 이름 변경
- 파일 크기 측정
등의 mock을 고려한 가상 함수들이 구현되어있습니다. 
> [feature] Add logger class and file system interface

- Testshell/command.h
- Testshell/main.cpp
- Testshell/test_script_command.cpp
- Testshell/test_shell.cpp
- Test Script "4_EraseAndWriteAging"
- shortcut/fullname 으로 호출 시 성공 UT 작성
- shortcut/fullname 으로 호출 시 실패 UT 작성
> [feature] TestShell Script 4

- Testshell/ssd_exe.cpp
- Testshell/test_shell.cpp
- Testshell/test_shell.h
- Dead code 삭제
- 초기에 작성했으나 사용하지 않는 class 를 삭제합니다.
> [cleancode] Dead Code 삭제

- Testshell/ssd_exe.cpp
- Testshell/ssd_exe.h
- flush 구현부 누락 수정
- pr merge conflict 해결 중 구현부 누락하여 새로 수정 드립니다.
> [hotfix] conflict 수정 시 flush 구현 부분 누락 수정

- .gitignore
- buffer gitignore 경로 수정
- buffer gitignore 경로 수정
> [docs] Update .gitignore

- SSD/SSD.vcxproj.filters
- SSD/ssd_cmd_buffer.cpp
- SSD/ssd_cmd_buffer.h
- SSD/ssd_cmd_buffer_control.cpp
- SSD/ssd_cmd_buffer_control.h
- SSD/ssd_cmd_buffer_control_test.cpp
- buffer 알고리즘 적용을 위해 필요한 API 구현건 입니다.
- Empty buffer shift 기능 및.
buffer의 cmd, lba, size, value return 할 수 있도록 구현
> [Feature] Buffer Control 기능 추가건

- Testshell/erase_command.cpp
- Testshell/erase_range_command.cpp
- Testshell/exit_command.cpp
- Testshell/flush_command.cpp
- Testshell/fullread_command.cpp
- Testshell/fullwrite_command.cpp
- Testshell/help_command.cpp
- Testshell/main.cpp
- Testshell/read_command.cpp
- Testshell/test_script_command.cpp
- Testshell/test_shell.cpp
- Testshell/test_shell.h
- Testshell/write_command.cpp
- 터미널 출력 포맷 수정 (예시와 동일하게)
- 터미널 출력 포맷 수정 (예시와 동일하게)
- 테스트 케이스 수정
- Erase 커맨드 Done 출력
- 사용되지 않는 헤더 제거
> [refactor] Modify std output formats

- SSD/ssd_cmd_buffer_control.cpp
- SSD/ssd_cmd_buffer_control.h
- SSD/ssd_cmd_buffer_control_test.cpp
- SSD/ssd_driver.cpp
-  Buffer Erase 기능 추가하였습니다
- erase하는 구간에 해당하는 LBA를 Write하는 buffer가 있으면 Write Buffer삭제
- erase하는 구간과 겹치는/연속되는 LBA의 erase가 있으면 erase 병합 ( 10이 넘어도 일단 병합하고 나중에 flush할 때 10씩 나눔)
> [feature] update buffer erase

- Testshell/command.h
- Testshell/test_script_command.cpp
Reverts thk-test2/SSD-CodeClimbers#62
TestShell Refactoring 결과물 먼저 merge 이후 다시 PR 넣겠습니다.
> Revert "Refactoring/test script"

- Testshell/command.h
- Testshell/test_script_command.cpp
- 테스트 스크립트 함수 리팩토링
- 공통 구문 함수로 추출
> [refactor] refactor testscript functions

- SSD/ssd_cmd_buffer_control.cpp
- SSD/ssd_cmd_buffer_control.h
- SSD/ssd_cmd_buffer_control_test.cpp
- SSD/ssd_driver.cpp
- SSD/ssd_driver_test.cpp
- SSD - CMD buffer Read 기능 작성
- Buffer 내부 Read 가능한 값이 있을경우 nand_output.txt 참조가 아닌 buffer 만 참조하도록 변경
> [Feature] cmd Buffer (Read) 구현 및 UT 작성 

- Testshell/main.cpp
- 변수명 변경 시 누락됐던 것을 수정합니다.
- SsdExeApator -> SsdApator
> [hotfix] TestShell build error - 변수명 변경 누락건

- TEST_SCENARIO.md
> [test] add test scenario

- SSD/SSD.vcxproj
- SSD/file_iostream.cpp
- SSD/file_iostream.h
- SSD/ssd_cmd_buffer_control.cpp
- SSD/ssd_cmd_buffer_control.h
- SSD/ssd_driver.cpp
- SSD/ssd_driver.h
- SSD/ssd_driver_test.cpp
- rearrange code
- method화 진행
- SRP 준수하도록 method 위치 변경
- ssddriver쪽 함수 선언/정의 분리
> [Refact] rearrange code

- Testshell/file_system_interface.cpp
- Testshell/file_system_interface.h
- Testshell/logger.cpp
- Testshell/logger.h
- Testshell/logger_test.cpp
- 로그파일이 최상위 디렉토리에 저장되어 지저분해짐
- log/ 폴더 생성 후 해당 폴더에 저장
> [feature] Logger save log files in log/ folder

- Testshell/fullread_command.cpp
- Full Read Command 함수 리팩토링
- 클린코드 적용
> [refactor] Refactor FullReadCommand execute
